# Default config for sway
#
# Copy this to ~/.config/sway/config and edit it to your liking.
#
# Read `man 5 sway` for a complete reference.

# variables moved to 01-variables.conf

# output moved to 02-output.conf

# idle moved to 03-idle.conf

# input moved to 04-input.conf

### Key bindings

# basic bindings moved to 05-00-keybindings-basic.conf

# moving around moved to 05-01-keybindings-moving.conf

# workspaces moved to 05-02-keybindings-workspaces.conf

# layout moved to 05-03-keybindings-layout.conf

# scratchpad moved to 05-04-keybindings-scratchpad.conf

# resizing moved to 05-05-keybindings-resizing.conf

# utilities moved to 05-06-keybindings-utilities.conf

# bar moved to 06-bar.conf